apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.selectorLabel }}
  name: {{ .Values.fullName}}
spec:
  ports:
    - name: smtp
      port: {{ .Values.service.smtp }}
      targetPort: smtp
    - name: imap
      port: {{ .Values.service.imap }}
      targetPort: imap
  type: ClusterIP